"""init

Revision ID: a6548fbacf20
Revises: 
Create Date: 2025-08-01 21:29:40.153348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6548fbacf20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('PEOPLE_TRAFFIC_COUNTING', 'RASTA', 'FOOD', 'ANIMAL_CLASSIFIER', name='cameratype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('camera_rois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ENTER', 'EXIT', name='actiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_roi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('roi_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['roi_id'], ['camera_rois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameraRoiId', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ENTER', 'EXIT', name='actiontype'), nullable=False),
    sa.Column('animal_type', sa.String(length=100), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cameraRoiId'], ['camera_roi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameraRoiId', sa.Integer(), nullable=False),
    sa.Column('food_types', sa.JSON(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cameraRoiId'], ['camera_roi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rasta_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cameraRoiId', sa.Integer(), nullable=False),
    sa.Column('peopleCount', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cameraRoiId'], ['camera_roi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rasta_record')
    op.drop_table('food_record')
    op.drop_table('animal_record')
    op.drop_table('camera_roi')
    op.drop_table('people_record')
    op.drop_table('camera_rois')
    op.drop_table('camera')
    # ### end Alembic commands ###
